#!/bin/bash
# /etc/init.d/pushthebutton

### BEGIN INIT INFO
# Provides:		pushthebutton
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Refault-Stop:		0 1 6
# Short-Description:	Push the button
# Descripton:		This service is used to manage a button and an LED attached to the RPi GPIO pins
### END INIT INFO

case "$1" in
	start)
		echo "Starting pushthebutton"
		/home/pi/workspace/pushthebutton/pushthebuttond
		;;
	stop)
		echo "Stopping pushthebutton"
		killall pushthebuttond
		;;
	*)
		echo "Usage: /etc/init.d/pushthebutton start|stop"
		exit 1
		;;
esac

exit 0


